// Code generated by proto-gen-go-lib-contract . DO NOT EDIT.
// Source: "github.com/aksanart/tracker_service/contract"

package contract

import (
	"context"
)

type TrackerService interface {
	HealthCheck(context.Context, *EmptyRequest) (*DefaultResponse, error)
	CreateTracker(context.Context, *CreateTrackerReq) (*DefaultResponse, error)
	UpdateTracker(context.Context, *UpdateTrackerReq) (*DefaultResponse, error)
	ListTracker(context.Context, *EmptyRequest) (*ListTrackerResponse, error)
	DetailTracker(context.Context, *IDTrackerReq) (*DetailTrackerResponse, error)
	DeleteTracker(context.Context, *IDTrackerReq) (*DefaultResponse, error)
}
