// Code generated by proto-gen-go-kit-transport. DO NOT EDIT.
// * Source: "github.com/aksan/weplus/apigw/contract/contract/grpc.proto"

package transport

import (
	"context"

	"github.com/aksan/weplus/apigw/contract"
)

type UseCaseContract interface {
	HealthCheck(ctx context.Context, request *contract.EmptyRequest) (response *contract.DefaultResponse, err error)                                        // (unary)
	Register(ctx context.Context, request *contract.RegisterReq) (response *contract.DefaultResponse, err error)                                            // (unary)
	Login(ctx context.Context, request *contract.RegisterReq) (response *contract.LoginResponse, err error)                                                 // (unary)
	ListVehicle(ctx context.Context, request *contract.ListVehicleReq) (response *contract.ListVehicleResponse, err error)                                  // (unary)
	HistoryLocationVehicle(ctx context.Context, request *contract.HistoryLocationVehicleReq) (response *contract.HistoryLocationVehicleResponse, err error) // (unary)
	CreateVehicle(ctx context.Context, request *contract.CreateVehicleReq) (response *contract.DefaultResponse, err error)                                  // (unary)
	UpdateVehicle(ctx context.Context, request *contract.UpdateVehicleReq) (response *contract.DefaultResponse, err error)                                  // (unary)
	DeleteVehicle(ctx context.Context, request *contract.IDVehicleReq) (response *contract.DefaultResponse, err error)                                      // (unary)
	LiveTrackingOne(ctx context.Context, request *contract.LiveTrackingOneReq, stream contract.ApiGateway_LiveTrackingOneServer) (err error)                // (server stream)
}

type transport struct {
	contract.UnimplementedApiGatewayServer
	UseCase UseCaseContract
}

func NewTransport(ctx context.Context, useCase UseCaseContract) *transport {
	return &transport{
		UseCase: useCase,
	}
}
