// Code generated by proto-gen-svc-transport. DO NOT EDIT.
// Folder	: "github.com/aksan/weplus/apigw/contract"
// File		: "contract/grpc.proto"

package transport

import (
	"context"

	"github.com/aksan/weplus/apigw/contract"
)

func (t transport) ListVehicle(ctx context.Context, request *contract.ListVehicleReq) (response *contract.ListVehicleResponse, err error) {
	// * Bridging to usecase related method
	return t.UseCase.ListVehicle(ctx, request)
}
