// Code generated by proto-gen-svc-transport. DO NOT EDIT.
// Folder	: "github.com/aksan/weplus/apigw/contract"
// File		: "contract/grpc.proto"

package transport

import (
	"github.com/aksan/weplus/apigw/contract"
	"go.elastic.co/apm/v2"
)

func (t transport) LiveTrackingOne(request *contract.LiveTrackingOneReq, stream contract.ApiGateway_LiveTrackingOneServer) (err error) {

	span, ctx := apm.StartSpan(stream.Context(), "transport.LiveTrackingOne", "transport.internal")
	defer span.End()

	// * Bridging to usecase related method
	return t.UseCase.LiveTrackingOne(ctx, request, stream)
}
