FROM golang:1.21-alpine
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go test -v -coverprofile=coverage.out ./...
RUN go tool cover -html=coverage.out -o coverage.html
CMD ["go", "test", "-v", "-coverprofile=coverage.out", "./..."]
