// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/repo_interface/mongo_iface.go
//
// Generated by this command:
//
//	mockgen.exe -source ./repository/repo_interface/mongo_iface.go -destination ./repository/repomock/mongo_iface.go -package repomock echo mongo_iface.go
//
// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"

	model "github.com/aksanart/tracker_service/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMongoInterface is a mock of MongoInterface interface.
type MockMongoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMongoInterfaceMockRecorder
}

// MockMongoInterfaceMockRecorder is the mock recorder for MockMongoInterface.
type MockMongoInterfaceMockRecorder struct {
	mock *MockMongoInterface
}

// NewMockMongoInterface creates a new mock instance.
func NewMockMongoInterface(ctrl *gomock.Controller) *MockMongoInterface {
	mock := &MockMongoInterface{ctrl: ctrl}
	mock.recorder = &MockMongoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoInterface) EXPECT() *MockMongoInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMongoInterface) Create(ctx context.Context, data *model.Tracker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMongoInterfaceMockRecorder) Create(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMongoInterface)(nil).Create), ctx, data)
}

// Delete mocks base method.
func (m *MockMongoInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMongoInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMongoInterface)(nil).Delete), ctx, id)
}

// FindAllTracker mocks base method.
func (m *MockMongoInterface) FindAllTracker(ctx context.Context) ([]*model.Tracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllTracker", ctx)
	ret0, _ := ret[0].([]*model.Tracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllTracker indicates an expected call of FindAllTracker.
func (mr *MockMongoInterfaceMockRecorder) FindAllTracker(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTracker", reflect.TypeOf((*MockMongoInterface)(nil).FindAllTracker), ctx)
}

// FindById mocks base method.
func (m *MockMongoInterface) FindById(ctx context.Context, id string) (*model.Tracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*model.Tracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockMongoInterfaceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockMongoInterface)(nil).FindById), ctx, id)
}

// FindByVehicleId mocks base method.
func (m *MockMongoInterface) FindByVehicleId(ctx context.Context, vehicleId string) (*model.Tracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByVehicleId", ctx, vehicleId)
	ret0, _ := ret[0].(*model.Tracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByVehicleId indicates an expected call of FindByVehicleId.
func (mr *MockMongoInterfaceMockRecorder) FindByVehicleId(ctx, vehicleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByVehicleId", reflect.TypeOf((*MockMongoInterface)(nil).FindByVehicleId), ctx, vehicleId)
}

// HealthCheck mocks base method.
func (m *MockMongoInterface) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockMongoInterfaceMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockMongoInterface)(nil).HealthCheck), ctx)
}

// Update mocks base method.
func (m *MockMongoInterface) Update(ctx context.Context, id string, data *model.Tracker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMongoInterfaceMockRecorder) Update(ctx, id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMongoInterface)(nil).Update), ctx, id, data)
}

// UpdateLocation mocks base method.
func (m *MockMongoInterface) UpdateLocation(ctx context.Context, vehicleId string, data *model.Tracker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, vehicleId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockMongoInterfaceMockRecorder) UpdateLocation(ctx, vehicleId, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockMongoInterface)(nil).UpdateLocation), ctx, vehicleId, data)
}
