// Code generated by proto-gen-go-lib-contract . DO NOT EDIT.
// Source: "github.com/aksan/weplus/apigw/contract"

package contract

import (
	"context"
)

type ApiGateway interface {
	HealthCheck(context.Context, *EmptyRequest) (*DefaultResponse, error)
	Register(context.Context, *RegisterReq) (*DefaultResponse, error)
	Login(context.Context, *RegisterReq) (*LoginResponse, error)
	ListVehicle(context.Context, *ListVehicleReq) (*ListVehicleResponse, error)
	HistoryLocationVehicle(context.Context, *HistoryLocationVehicleReq) (*HistoryLocationVehicleResponse, error)
	CreateVehicle(context.Context, *CreateVehicleReq) (*DefaultResponse, error)
	UpdateVehicle(context.Context, *UpdateVehicleReq) (*DefaultResponse, error)
	DeleteVehicle(context.Context, *IDVehicleReq) (*DefaultResponse, error)
	LiveTrackingOne(context.Context, *LiveTrackingOneReq) (*LiveTrackingOneResp, error)
}
